### ISSUE TITLE
mvwin doesn't work if window is created with zero coordinates.

### ISSUE THREAD

**Issue by derDere** [gittup/ncurses#3]
Hi,
so using c++ if I create a window (newwin) using 0,0 as start location its not possible to change the window location using mvwin. If I create the window using 1,1 as start location it's no problem.
Here is the code I tested it with:

mvwin dosen't work:
```
#include <ncurses.h>
#include <stdlib.h>
void quit();
int main(int argc, char** argv) {
  initscr();
  atexit(quit);
  curs_set(0);
  noecho();
  WINDOW *win = newwin(0,0,0,0); // <-- Doesn't Works with mvwin
  mvwin(win,10,10);
  wresize(win,10,10);
  refresh();
  box(win,0,0);
  wrefresh(win);
  getch();
  return 0;//*/
}
void quit() {
  endwin();
}
```

mvwin works:
```
#include <ncurses.h>
#include <stdlib.h>
void quit();
int main(int argc, char** argv) {
  initscr();
  atexit(quit);
  curs_set(0);
  noecho();
  WINDOW *win = newwin(1,1,0,0); // <-- Works with mvwin
  mvwin(win,10,10);
  wresize(win,10,10);
  refresh();
  box(win,0,0);
  wrefresh(win);
  getch();
  return 0;//*/
}
void quit() {
  endwin();
}
```

I already left a bug at ubuntu one not 100% sure if its the same project.

**Comment by gittup** [comment]
This is not the official ncurses project, just a personal clone with some modifications for use with the tup build system. You might want to try one of the mailing lists that are listed in https://www.gnu.org/software/ncurses/ncurses.html
